name: make PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Pull docker (paperist/texlive-ja)
        run: docker pull paperist/texlive-ja:latest

      - name: Download jlisting.sty
        run: |
          wget https://osdn.net/projects/mytexpert/downloads/26068/jlisting.sty.bz2
          bunzip2 jlisting.sty.bz2

      - name: Make PDF
        run: docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main.tex

      - name: Move to output
        run: |
          mkdir -p output
          mv main.pdf output

      - uses: actions/upload-artifact@v2
        with:
          name: library-PDF
          path: output/main.pdf

      - name: Deploy PDF to release branch
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Deploy PDF by GitHub Actions ($GITHUB_WORKFLOW)'
          add: output
          branch: release
          default_author: github_actions
