name: make PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Pull docker (paperist/texlive-ja)
        run: docker pull paperist/texlive-ja:latest

      - name: Download jlisting.sty
        run: |
          wget https://osdn.net/projects/mytexpert/downloads/26068/jlisting.sty.bz2
          bunzip2 jlisting.sty.bz2

      - name: Make PDF
        run: |
          docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main_1col.tex
          docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main_2col.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: library-PDF
          path: main_*.pdf

  pdf-auto-commit:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Download PDF
        uses: actions/download-artifact@v3
        with:
          name: library-PDF

      - name: Commit PDF
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update Library PDF'
          default_author: github_actions
          add: '*.pdf'
