name: make PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Pull docker (paperist/texlive-ja)
        run: docker pull paperist/texlive-ja:latest

      - name: Download jlisting.sty
        run: |
          wget https://osdn.net/projects/mytexpert/downloads/26068/jlisting.sty.bz2
          bunzip2 jlisting.sty.bz2

      - name: Make PDF
        run: docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main.tex

      - name: Move to output
        run: |
          mkdir -p output
          mv main.pdf output

      - uses: actions/upload-artifact@v2
        with:
          name: library-PDF
          path: output/main.pdf

      #  以下は保護されたブランチに対しては失敗する
      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     add: output
      #     default_author: github_actions
