name: make PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Pull docker (paperist/texlive-ja)
        run: docker pull paperist/texlive-ja:latest

      - name: Download jlisting.sty
        run: |
          wget https://osdn.net/projects/mytexpert/downloads/26068/jlisting.sty.bz2
          bunzip2 jlisting.sty.bz2

      - name: Make PDF
        run: |
          docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main_1col.tex
          docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main_2col.tex

      - name: Move to output
        run: |
          mkdir -p output
          mv main_*.pdf output

      - uses: actions/upload-artifact@v2
        with:
          name: library-PDF
          path: output/main_*.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
