name: verify

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**.hpp'
      - '**.cpp'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.hpp'
      - '**.cpp'

jobs:
  oj-verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip3 install online-judge-verify-helper

      - name: Run tests
        run: oj-verify run --jobs 2

