name: verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  skip-check:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          skip_after_successful_duplicate: 'false'
          paths: '["**.hpp", "**.cpp", "**.tex"]'

  oj-verify:
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip3 install online-judge-verify-helper

      - name: Cache test cases
        uses: actions/cache@v2
        with:
          path: ./.verify-helper/cache
          key: ${{ runner.os }}-verify-helper-${{ hashFiles('**/*.test.cpp') }}
          restore-keys: |
            ${{ runner.os }}-verify-helper-

      - name: Run tests (on main branch)
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DROPBOX_TOKEN: ${{ secrets.ATCODER_DROPBOX_TOKEN }}
        run: oj-verify run --jobs 2

      - name: Run tests (on other branch)
        if: github.ref != 'refs/heads/main'
        env:
          DROPBOX_TOKEN: ${{ secrets.ATCODER_DROPBOX_TOKEN }}
        run: oj-verify run --jobs 2

  build:
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Pull docker (paperist/texlive-ja)
        run: docker pull paperist/texlive-ja:latest

      - name: Download jlisting.sty
        run: |
          wget https://osdn.net/projects/mytexpert/downloads/26068/jlisting.sty.bz2
          bunzip2 jlisting.sty.bz2

      - name: Make PDF
        run: |
          docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main_1col.tex
          docker run --rm -v $PWD:/workdir paperist/texlive-ja:latest latexmk main_2col.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: library-PDF
          path: main_*.pdf

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [oj-verify, build]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Download PDF
        uses: actions/download-artifact@v3
        with:
          name: library-PDF

      - name: Commit PDF
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update Library PDF'
          default_author: github_actions
          add: '*.pdf'

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.YNUCPC_ACCESS_TOKEN_APP_ID }}
          private_key: ${{ secrets.YNUCPC_ACCESS_TOKEN_APP_PRIVATE_KEY }}

      - name: Generate documents
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ steps.generate_token.outputs.token }}
        run: oj-verify docs
